services:
  postgres:
    image: 'postgres:latest'
    env_file:
      secrets
    environment:
      - 'POSTGRES_DB=${SECRETS_DATABASE_NAME}'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
