services:
  postgres:
    image: 'postgres:16.9-bullseye'
    env_file:
      secrets
    environment:
      - 'POSTGRES_DB=${SECRETS_DATABASE_NAME}'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '${SECRET_PORT}'
