services:
  postgres:
    image: 'postgres:16.9-bullseye'
    env_file:
      secrets
    environment:
      - 'POSTGRES_DB=my-db-dada'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
