name: Deploy to Raspberry Pi

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Deploy with Docker Compose
#        run: docker-compose up -d

      - name: Setup SSH key
        run: |
          echo "${{ secrets.PI_SSH_KEY }}" > id_rsa
          chmod 600 id_rsa

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.PI_SSH_PORT }} -i id_rsa ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }} << 'EOF'
          rm -rf ${{ github.event.repository }}
          git clone git@github.com:${{ github.repository }}.git 
          cd demo2
          echo "${{ secrets.PI_DECRYPTION_PASS }}" > pass_file
          openssl enc -d -aes-256-cbc -pbkdf2 -iter 1000 -salt -in secrets.enc -out secrets -pass "file:pass_file"
          EOF